### ISSUE TITLE
No response after longer interactions

### ISSUE THREAD

**Issue by ufulu** [bitswired/ai-chat-app#13] opened 2023-03-08 22:45 UTC
I don’t know if this is a bug or an issue on openai’s api side. After longer constant conversations going back and forth suddenly no responses come back. As soon as I open a new chat I am good to go again and can continue interacting with the api until it stops again. Can you give me a hint as to how I might be able to debug this and shed some more light onto this issue?

Alternatively some error messages in the UI might be helpful for the user to understand what’s going on.

**Comment by ufulu** [comment] 2023-03-08 22:49
I will run with yarn dev tomorrow and see if I can find something.

**Comment by minisaurus** [comment] 2023-03-09 08:07
I've noticed this too. It stops responding after about 12-15 responses.

**Comment by jimzer** [comment] 2023-03-13 12:32
Hey guys :) 
Thanks for reporting the issue.

The problem is that we have a maximum of ~4000 tokens for the context, and for now, the app is sending the entire chat as a context.
I need to implement a "forgetting" behavior.

However, I don't know the best way to do it.

Should we only keep the most recent context?

**Comment by jimzer** [comment] 2023-03-13 18:51
I close this issue since #15 fixed it for now.

@ufulu You can look at the changes and open a new issue if you prefer another behavior for forgetting the history.

**Comment by jimzer** [comment] 2023-03-13 18:52
I close this issue since #15 fixed it for now.

@ufulu You can look at the changes and open a new issue if you prefer another behavior for forgetting the history.

**Closed by jimzer** 2023-03-13 18:52 UTC
Labels: bug
